Restructured Lua File, Added spray and shape brush, Added extensive help text
gynt/stronghold-mapeditortools pull request #3
Opened 2021-04-11 22:30 UTC by TheRedDaemon

- The issue of the shape-brush easily exceeding the action limit is of course still there.
- The auto generated command list still does not contain "help", so I added it via HELP. 😉

2021-04-14 12:00 UTC, gynt requested changes
Maybe you can add @author documentation statements to each of your functions, so we can get back to you if there is development or somebody has a question.

2021-04-14 12:00 UTC, gynt commented on shc-mapeditortools.lua
> +  -- I lack LUA knowledge, so there might be a more efficient way than a second array...
I think this approach is fine. You can remove the comment.

2021-04-14 12:00 UTC, gynt commented on shc-mapeditortools.lua
> +    SUGGESTION: "point" is more a rotation
Point reflection could be described as rotation around the Z axis as well: https://en.wikipedia.org/wiki/Point_reflection

2021-04-14 12:00 UTC, gynt commented on shc-mapeditortools.lua
> +    -> maybe add the ability to apply a point rotation to the action instead
Currently, I am repeatedly applying a command at certain x and y. How would you describe point rotation in terms of game actions?

2021-04-14 12:00 UTC, gynt commented on shc-mapeditortools.lua
> +function applyBrushModification(x, y, size)
I like your new version of applyMirrors, but can you maybe separate applyMirrors from applyBrushModification?
I would rather have a list of transformations/modifications that the original coords go through. See my comment at applyBrush too
```lua
ActiveTransformations = {
   applyBrushModification,
   applyMirrors
}
```

2021-04-14 12:00 UTC, gynt commented on shc-mapeditortools.lua
> +  coordlist = {} -- If I understand LUA right, this is a global variable and is reset every call, right?
Correct, you can change it to local, but I like the fact you can inspect the coordlist in the console.
You can remove the comment.

2021-04-14 12:00 UTC, gynt commented on shc-mapeditortools.lua
> +    TODO?: shape coords are not applied in a very structured order, currently it seems to be:
I am not sure I understand what this means.

2021-04-14 12:00 UTC, gynt commented on shc-mapeditortools.lua
> +  coordinatelist = applyBrushModification(x, y, 1)
```lua
  coordinatelist = {x, y}
  for key, func in pairs(ActiveTransformations) do
    coordinatelist = func(coordinatelist, 1)
  end
```

2021-04-14 13:49 UTC, TheRedDaemon commented
Just a question outside the remarks:
The @author statements... should I add them only to the functions I mainly wrote, or to the comments in general?
Or is there a comment convention you would prefer? A general form basically?
(Currently I am switching between (--) and (--[[ ]]--) comments quite liberally for example. That does not really feel right.)

2021-04-14 14:45 UTC, TheRedDaemon commented on shc-mapeditortools.lua
> +  -- I lack LUA knowledge, so there might be a more efficient way than a second array...
Ok, removed the comment.

2021-04-14 14:59 UTC, TheRedDaemon commented on shc-mapeditortools.lua
> +    -> maybe add the ability to apply a point rotation to the action instead
I tried to describe a potential other modification.
Basically, you could see the point mirror also as a 180 degree rotation around the center.
Now, the most basic extension of this would be to apply 4 points in total. 1 being the original, the other 3 being the point rotated 90, 180 and 270 degrees around the center, which would allow to create all edges of a map equally.

You might also support only three point, or five, six, etc. That would be the feature I would try to implement once this pull request is done.
But I am also uncertain, whether "point" should be removed from the normal "mirror" functions in this case, or not.

2021-04-14 15:00 UTC, TheRedDaemon commented on shc-mapeditortools.lua
> +    SUGGESTION: "point" is more a rotation
I always fail in regards to semantics... 😅
However, the reason why I wrote this is explained [HERE](https://github.com/gynt/stronghold-mapeditortools/pull/3#discussion_r613327180)

2021-04-14 15:28 UTC, TheRedDaemon commented on shc-mapeditortools.lua
> +    TODO?: shape coords are not applied in a very structured order, currently it seems to be:
Which part?

BUG? -> I should change the wording, you already tolled me the reason for the limit on discord.

TODO? -> The order of coords is a bit messy at the moment. This might be ok or not, so it is also more a question.
For example, if I use the "shape" brush with the shape "line" and two mirrors and draw a 3 coord line, then the coords might have the following order: (numbers)
```
 1     |     10
  2    |    7
   3   |   4
_______|_______
       |
   5   |   6
  8    |    9
11     |     12
```
Now, this might be an issue... or not. It certainly has an effect if stuff is applied which can not be placed without a bit of space. Trees for example, or big rocks.

The question would be: Is this an issue worth tackling, or do we think of coords like we think of an unordered list? Without guarantees on apply order?

2021-04-14 15:33 UTC, TheRedDaemon commented on shc-mapeditortools.lua
> +  coordinatelist = applyBrushModification(x, y, 1)
So, the functions in ActiveTransformations are free to either modify coordinatelist and return it again, or to return something else, right?
Or would you prefer it if the funcs returned a new array/table for every modification?

2021-04-14 21:03 UTC, gynt commented on shc-mapeditortools.lua
> +    TODO?: shape coords are not applied in a very structured order, currently it seems to be:
Oh man, so complicated! This only matters for game actions that are not commutative (reordering the order produces a different result). Placing textures like oasis is commutative, so we do not care. Creating hills is not commutative I believe, but to be honest, I have no idea if that is correct. I would say to leave this open and documented for the future! I like the picture you made in your comment, you can insert that in the documentation.

2021-04-14 21:06 UTC, gynt commented on shc-mapeditortools.lua
> +  coordinatelist = applyBrushModification(x, y, 1)
Correct. I think it is intuitive for a programmer to return the coords they want. But another programmer could strongly prefer `table.insert()` syntax, which it also supports easily.

2021-04-14 21:08 UTC, gynt commented
Oh I was mainly talking about the functions you wrote. But it makes more sense that you add author to the comments that are about future ideas or potential issues!

2021-04-14 21:11 UTC, gynt commented on shc-mapeditortools.lua
> +    coordinatelist = func(coordinatelist, 1)
should be: `coordinatelist = func(coordinatelist, size)`

2021-04-15 19:50 UTC, TheRedDaemon commented on shc-mapeditortools.lua
> +    coordinatelist = func(coordinatelist, 1)
Should be fixed now.

2021-04-15 19:51 UTC, TheRedDaemon commented on shc-mapeditortools.lua
> +    TODO?: shape coords are not applied in a very structured order, currently it seems to be:
Added explanation... and a way to configure it for the mirror function. 😅

2021-04-15 19:52 UTC, TheRedDaemon commented on shc-mapeditortools.lua
> +  coordlist = {} -- If I understand LUA right, this is a global variable and is reset every call, right?
Not relevant anymore for new pipeline

2021-04-15 19:52 UTC, TheRedDaemon commented on shc-mapeditortools.lua
> +function applyBrushModification(x, y, size)
Separated. Part of new pipeline

2021-04-15 19:55 UTC, TheRedDaemon commented
Ok, added the requested stuff, including (at)author statements. (@author links to some github project... good name for traffic 😄 )
Ready for next review.

2021-04-16 12:32 UTC, gynt approved these changes
Nice idea to extend the point reflection to include an X number of reflections.

2021-04-16 12:32 UTC, merged